// types.rs — The universal type system.
//
// Every language adapter converts to and from these types. The active
// member of GluValue is determined by the signature's type tag, NOT
// embedded in the value itself.
//
// Layout must match the C++ mirror (adapters/cpp/include/glucore_export.hpp)
// and the Python ctypes mirror (adapters/python/bindings.py) EXACTLY.
// The C++ adapter has a static_assert for this; the Python adapter
// verifies via round-trip tests.

use std::os::raw::c_char;

/// Pointer + length pair used by the String and Buffer variants of GluValue.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct GluSlice {
    pub ptr: *const u8,
    pub len: usize,
}

/// Runtime value carried across the FFI boundary.
///
/// Plain union — type info lives in GluSignature, not embedded in GluValue.
/// Per Constraint 4 (copy semantics): for String/Buffer, Rust owns its own
/// copy. The pointer+len in `string`/`buffer` reference either:
///   * argument direction (Python → Rust): Python's buffer, valid for the
///     duration of the call. Rust copies into its own String/Vec<u8>.
///   * return direction (Rust → Python): Rust-allocated memory, leaked to
///     live for the process lifetime (correctness first, optimize later).
#[repr(C)]
#[derive(Clone, Copy)]
pub union GluValue {
    pub float: f64,
    pub int: i64,
    pub string: GluSlice,
    pub buffer: GluSlice,
}

/// Compile-time tag identifying one of the supported native types.
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum GluTypeTag {
    Int = 0,
    Float = 1,
    String = 2,
    Buffer = 3,
    Handle = 4,
    Void = 5,
}

/// Per-function signature metadata, generated by the #[export] macro and
/// emitted as a `static` alongside each wrapper. Consumed by Task 2
/// (registration) and Task 4 (FFI-safe variant for Python validation).
#[repr(C)]
#[derive(Clone, Copy)]
pub struct GluSignature {
    pub params: &'static [GluTypeTag],
    pub return_type: GluTypeTag,
}

/// FFI-safe variant of GluSignature. `&'static [GluTypeTag]` is a Rust slice
/// (fat pointer: ptr + len) and is not directly C-ABI-compatible. This struct
/// decomposes it into a raw pointer + count, which ctypes can read.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct GluSignatureFFI {
    pub param_types: *const GluTypeTag,
    pub param_count: usize,
    pub return_type: GluTypeTag,
}

impl GluSignatureFFI {
    pub fn empty() -> Self {
        GluSignatureFFI {
            param_types: std::ptr::null(),
            param_count: 0,
            return_type: GluTypeTag::Void,
        }
    }
}

/// Status code returned to Python on errors.
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum GluStatus {
    Ok = 0,
    Runtime = 1,
    InvalidArgs = 2,
    NotFound = 3,
    LinkDenied = 4, // Ahead of Task 5 — harmless until used
}

/// Result of an exported call.
#[repr(C)]
pub struct GluResult {
    pub status: GluStatus,
    pub value: GluValue,
    pub message: *const c_char,
}

/// Function pointer type for a generated wrapper.
pub type GluWrapper = extern "C" fn(*const GluValue, usize) -> GluResult;

/// A single exported function — name + wrapper + signature.
/// Task 4: the signature is now carried alongside the wrapper so the core
/// can answer `glucore_get_signature` queries without cross-binary inventory
/// walks.
#[repr(C)]
pub struct GluExportEntry {
    pub name: *const c_char,
    pub wrapper: GluWrapper,
    pub signature: GluSignatureFFI,
}

/// Collectible record produced by `#[glucore::export]` for each function.
/// Iterated at module-registration time to build the export table — replaces
/// the manual EXPORTS array (Task 2).
pub struct GluExport {
    pub name: &'static str,
    pub wrapper: GluWrapper,
    pub signature: GluSignature,
}

inventory::collect!(GluExport);

/// A module's export table.
#[repr(C)]
pub struct GluModule {
    pub name: *const c_char,
    pub entries: *const GluExportEntry,
    pub count: usize,
}

impl GluTypeTag {
    pub(crate) fn from_u8(v: u8) -> Result<Self, String> {
        match v {
            0 => Ok(GluTypeTag::Int),
            1 => Ok(GluTypeTag::Float),
            2 => Ok(GluTypeTag::String),
            3 => Ok(GluTypeTag::Buffer),
            4 => Ok(GluTypeTag::Handle),
            5 => Ok(GluTypeTag::Void),
            0xFF => Ok(GluTypeTag::Void), // "Void" tag in result
            _ => Err(format!("unknown GluTypeTag byte {}", v)),
        }
    }
}
